name: phppdfparser_com
services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8.4-fpm-alpine
    container_name: php_fpm
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
